<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        /**
         * promise
         * 接收一个函数作为参数，该函数的两个参数为resolve和reject两个函数
         */
        new Promise(
            /* 执行器 executor */
            function (resolve, reject) {
                // 一段耗时很长的异步操作

                resolve(); // 数据处理完成

                reject(); // 数据处理出错
            }
        )
            .then(function A() {
                // 成功，下一步
            }, function B() {
                // 失败，做相应处理
            });

        /**
         * promise.all()的用法
         * 接收数组作为参数
         * 返回该数组所有结果集（数组）
         */
        console.log('here we go');
        Promise.all([1, 2, 3])
            .then(all => {
                console.log('1：', all);
                return Promise.all([function () {
                    console.log('ooxx');
                }, 'xxoo', false]);
            })
            .then(all => {
                console.log('2：', all);
                let p1 = new Promise(resolve => {
                    setTimeout(() => {
                        resolve('I\'m P1');
                    }, 1500);
                });
                let p2 = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve('I\'m P2');
                    }, 1000);
                });
                let p3 = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve('I\'m P3');
                    }, 3000);
                });
                return Promise.all([p1, p2, p3]);
            })
            .then(all => {
                console.log('all', all);
            })
            .catch(err => {
                console.log('Catch：', err);
            });
        // here we go
        // 1: [1,2,3]
        // 2: [f,'xxoo', false]
        // all ["I'm P1", "I'm P2", "I'm P3"]

        /**
         * 建议不使用then的第二个参数接收错误
         * 而是使用catch接收
         * 原因是这么做更接近同步写法（try，catch）
         */
        // bad
        // promise.then(function (data) {
        //     // success
        // }, function (err) {
        //     // error
        // });

        // // good
        // promise.then(function (data) { //cb
        //     // success
        // })
        // .catch(function (err) {
        //     // error
        // });

        /**
         * promise 嵌套
         * 会先完成内部的promise实例的then方法
         * 完成之后，再执行外部promise的then方法
         */
        console.log('start');
        new Promise(resolve => {
            console.log('Step 1');
            setTimeout(() => {
                resolve(100);
            }, 1000);
        })
            .then(value => {
                return new Promise(resolve => {
                    console.log('Step 1-1');
                    setTimeout(() => {
                        resolve(110);
                    }, 1000);
                })
                    .then(value => {
                        console.log('Step 1-2');
                        return value;
                    })
                    .then(value => {
                        console.log('Step 1-3');
                        return value;
                    });
            })
            .then(value => {
                console.log(value);
                console.log('Step 2');
            });

        /**
         * 嵌套promise
         * 若内部的promise有定义catch捕获异常，则执行内部的catch
         * 否则执行外部的catch
         */
        console.log('start');
        new Promise(resolve => {
            console.log('Step 1');
            setTimeout(() => {
                resolve(100);
            }, 1000);
        })
            .then(value => {
                return new Promise(resolve => {
                    console.log('Step 1-1');
                    setTimeout(() => {
                        resolve(110);
                    }, 1000);
                })
                    .then(value => {
                        console.log('Step 1-2');
                        return value;
                    })
                    .then(value => {
                        throw new Error('出错了');
                    })
                    .catch(err => {
                        console.log('内部：' + err.message);
                    });
            })
            .then(value => {
                console.log(value);
                console.log('Step 2');
            })
            .catch(err => {
                console.log('外部：' + err.message);
            });
        // start
        // Step 1
        // Step 1-1
        // Step 1-2
        // 内部：出错了
        // undefined // 依旧走了最后的一个then
        // Step 2

        /**
         * promise已经完成，再.then()
         * 再任何地方生成promise队列，可以在后面追加任意then
         * 均会按队列顺序执行，接收上一次最后返回的值
         */
        console.log('start');

        let promise = new Promise(resolve => {
            setTimeout(() => {
                console.log('the promise fulfilled');
                resolve('hello, world');
            }, 1000);
        });

        setTimeout(() => {
            promise.then(value => {
                console.log(value);
            });
        }, 3000);

        // start
        // the promise fulfilled
        // hello, world （在 the promise fulfilled 输出后两秒后输出）

        /**
         * 假设doSomething和doSomethingElse返回的都是一个Promise实例
         * 以下四个问题的区别是什么
         * // 原问题地址：http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html
         * // 译文地址：http://fex.baidu.com/blog/2015/07/we-have-a-problem-with-promises/
         * // https://www.imooc.com/video/16619
         */

        // 问题一
        doSomething()
            .then(function () {
                return doSomethingElse();
            })
            .then(finalHandler);
            
        // 常见

        // 答案
        // doSomething
        // |-----------|
        //             doSomethingElse(undefined)
        //             |------------|
        //                          finalHandler(resultOfDoSomethingElse)
        //                          |------------|


        // 问题二
        doSomething()
            .then(function () {
                doSomethingElse();
            })
            .then(finalHandler);

        // 第一个then无return，视为返回空，finalHandler会立刻执行

        // 答案
        // doSomething
        // |------------------|
        //                    doSomethingElse(undefined)
        //                    |------------------|
        //                    finalHandler(undefined)
        //                    |------------------|


        // 问题三
        doSomething()
            .then(doSomethingElse())
            .then(finalHandler);

        // doSomethingElse带括号，直接执行，相当于传入promise实例
        // 因为doSomething接收的是一个promise实例而不是方法，所以忽视doSomethingElse返回的实例
        // doSomethingElse不在队列中，所以它返回的promise实例无关重要

        // 答案
        // doSomething
        // |------------------|
        // doSomethingElse(undefined)
        // |----------------------------------|
        //                    finalHandler(resultOfDoSomething)
        //                    |------------------|


        // 问题四
        doSomething()
            .then(doSomethingElse)
            .then(finalHandler);

        // 答案
        // doSomething
        // |-----------|
        //             doSomethingElse(resultOfDoSomething)
        //             |------------|
        //                         finalHandler(resultOfDoSomethingElse)
        //                         |------------------|
    </script>
</body>

</html>